name: re-nfa

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ocaml-compiler: 4.14.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Deps
        run: |
          opam pin add -n re-nfa.dev .
          opam install -t --deps-only .

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest
